"""
Generate the Gemma-3-4b-it mechanism CI tables for App L (cross-family
mechanism details).

Inputs:
- lora_intervention/results/ci_analysis_gemma.txt
  (already computed bootstrap 95% CIs from the runs documented in
  GEMMA_RUN_LOG.md §5.4b)

Outputs (paper/figures/):
- tab_gemma_probing.tex   — 8 late layers (L26-L33) x 3 probes (cond
                            discrimination, RI correct, PI correct)
- tab_gemma_logit_lens.tex — 3 cells (K=2/N=5, K=2/N=10, K=2/N=50) x
                             2 directions (RI / PI) at final layer L33

Run from project root:
    .venv/bin/python paper/scripts/generate_gemma_mechanism_tables.py
"""

import re
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent.parent
OUT_DIR = Path(__file__).resolve().parent.parent / "figures"
OUT_DIR.mkdir(exist_ok=True)
CI_FILE = _ROOT / "lora_intervention" / "results" / "ci_analysis_gemma.txt"


def fmt_delta_cell(delta, lo, hi):
    """Format Δ [lo, hi]; bold if CI excludes zero."""
    sign = "+" if delta >= 0 else "$-$"
    txt = f"{sign}{abs(delta):.2f}\\,[{lo:+.2f}, {hi:+.2f}]"
    excludes_zero = (lo > 0 and hi > 0) or (lo < 0 and hi < 0)
    return rf"\textbf{{{txt}}}" if excludes_zero else txt


def fmt_val_cell(val, lo, hi):
    return f"{val:.2f}\\,[{lo:.2f}, {hi:.2f}]"


def parse_probing():
    """Parse the PROBING CLASSIFIER block; rows look like:
    Cond discr (RI vs PI)    L26  1.000 [1.000, 1.000]   1.000 [1.000, 1.000]   +0.000 [+0.000, +0.000]
    """
    text = CI_FILE.read_text()
    block_match = re.search(
        r"PROBING CLASSIFIER.*?\n=+\n(.*?)\n=+\nLOGIT LENS",
        text, re.DOTALL,
    )
    if not block_match:
        raise RuntimeError("Probing block not found")
    block = block_match.group(1)
    # Skip header line ("Probe  Layer  base [..]  lora [..]  Δ [..]")
    rows = []
    line_re = re.compile(
        r"^\s*(?P<probe>.+?)\s+L(?P<layer>\d+)\s+"
        r"(?P<base>[0-9.+\-]+)\s*\[(?P<blo>[0-9.+\-]+),\s*(?P<bhi>[0-9.+\-]+)\]\s+"
        r"(?P<lora>[0-9.+\-]+)\s*\[(?P<llo>[0-9.+\-]+),\s*(?P<lhi>[0-9.+\-]+)\]\s+"
        r"(?P<delta>[+\-][0-9.]+)\s*\[(?P<dlo>[0-9.+\-]+),\s*(?P<dhi>[0-9.+\-]+)\]\s*$"
    )
    for line in block.splitlines():
        m = line_re.match(line)
        if m:
            rows.append(m.groupdict())
    return rows


def parse_logit_lens():
    text = CI_FILE.read_text()
    block_match = re.search(
        r"LOGIT LENS \(Gemma-3-4b-it\).*?\n=+\n(.*)$",
        text, re.DOTALL,
    )
    if not block_match:
        raise RuntimeError("Logit lens block not found")
    block = block_match.group(1)
    rows = []
    line_re = re.compile(
        r"^\s*K=(?P<K>\d+),N=(?P<N>\d+)\s+(?P<cond>[A-Z]+)\s+(?P<target>\S+)\s+L(?P<layer>\d+)\s+"
        r"(?P<base>[0-9.+\-]+)\s*\[(?P<blo>[0-9.+\-]+),\s*(?P<bhi>[0-9.+\-]+)\]\s+"
        r"(?P<lora>[0-9.+\-]+)\s*\[(?P<llo>[0-9.+\-]+),\s*(?P<lhi>[0-9.+\-]+)\]\s+"
        r"(?P<delta>[+\-][0-9.]+)\s*\[(?P<dlo>[0-9.+\-]+),\s*(?P<dhi>[0-9.+\-]+)\]\s*$"
    )
    for line in block.splitlines():
        m = line_re.match(line)
        if m:
            rows.append(m.groupdict())
    return rows


def make_probing_table(rows, out_path):
    """Group by layer; one row per layer; three Δ columns (cond / RI / PI)."""
    # Build per-(layer, probe) lookup
    by = {}
    for r in rows:
        key = (int(r["layer"]), r["probe"].strip())
        by[key] = r
    layers = sorted({k[0] for k in by.keys()})
    lines = [
        "% Auto-generated by paper/scripts/generate_gemma_mechanism_tables.py",
        r"\begin{tabular}{lccc}",
        r"\toprule",
        r"\textbf{Layer} & "
        r"\textbf{$\Delta$ Cond. discr.} & "
        r"\textbf{$\Delta$ RI correctness} & "
        r"\textbf{$\Delta$ CVQ correctness} \\",
        r"\midrule",
    ]
    for L in layers:
        cells = []
        for probe_label in ["Cond discr (RI vs PI)", "RI correctness", "PI correctness"]:
            r = by.get((L, probe_label))
            if r is None:
                cells.append("---")
            else:
                cells.append(fmt_delta_cell(
                    float(r["delta"]), float(r["dlo"]), float(r["dhi"])
                ))
        lines.append(f"  L{L} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"  saved {out_path}")


def make_logit_lens_table(rows, out_path):
    """One row per (K, N); columns: base RI, LoRA RI, ΔRI, base PI, LoRA PI, ΔPI."""
    by = {}
    for r in rows:
        key = (int(r["K"]), int(r["N"]), r["cond"])
        by[key] = r
    pairs = sorted({(int(r["K"]), int(r["N"])) for r in rows})
    lines = [
        "% Auto-generated by paper/scripts/generate_gemma_mechanism_tables.py",
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r" & \multicolumn{3}{c}{\textbf{$P(v_{\mathrm{first}})$ (RI)}} & "
        r"\multicolumn{3}{c}{\textbf{$P(v_{\mathrm{last}})$ (CVQ)}} \\",
        r"\cmidrule(lr){2-4} \cmidrule(lr){5-7}",
        r"$(K, N)$ & Base & +LoRA & $\Delta$ & Base & +LoRA & $\Delta$ \\",
        r"\midrule",
    ]
    for K, N in pairs:
        ri = by.get((K, N, "RI"))
        pi = by.get((K, N, "PI"))
        cells = []
        for r in [ri, pi]:
            if r is None:
                cells.extend(["---", "---", "---"])
                continue
            cells.append(fmt_val_cell(float(r["base"]), float(r["blo"]), float(r["bhi"])))
            cells.append(fmt_val_cell(float(r["lora"]), float(r["llo"]), float(r["lhi"])))
            cells.append(fmt_delta_cell(float(r["delta"]), float(r["dlo"]), float(r["dhi"])))
        lines.append(f"  $({K}, {N})$ & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"  saved {out_path}")


def main():
    print(f"Generating Gemma mechanism tables to {OUT_DIR} …")
    probing_rows = parse_probing()
    logit_rows = parse_logit_lens()
    print(f"  parsed {len(probing_rows)} probing rows, {len(logit_rows)} logit-lens rows")
    make_probing_table(probing_rows, OUT_DIR / "tab_gemma_probing.tex")
    make_logit_lens_table(logit_rows, OUT_DIR / "tab_gemma_logit_lens.tex")
    print("Done.")


if __name__ == "__main__":
    main()
