"""
Generate the LoRA result tables for §5.2.

Inputs:
- ARB held-out results: lora_intervention/results/main_eval_*.json
  (28 held-out (K, N) cells on ARBITRARY_SINGLE, base vs LoRA)
- SEM OOD results: lora_sem_validation_results.json + lora_sem_finish_results.json
  (4 held-out cells on SEMANTIC_MULTI, base vs LoRA)

Outputs (paper/figures/):
- tab_lora_arb.tex — ARB held-out cells, base vs LoRA, gap delta
- tab_lora_sem.tex — SEM OOD cells, base vs LoRA, gap delta

Run from project root:
    .venv/bin/python paper/scripts/generate_lora_tables.py
"""

import glob
import json
import sys
from pathlib import Path

_ROOT = Path(__file__).resolve().parent.parent.parent
OUT_DIR = Path(__file__).resolve().parent.parent / "figures"
OUT_DIR.mkdir(exist_ok=True)

# Share the heatmap helpers with generate_main_results so all tables use the
# same blue (accuracy) + red (gap magnitude) palette.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from generate_main_results import (  # noqa: E402
    fmt_acc_cell, fmt_gap_cell, _acc_shade, _gap_shade,
)


def fmt_acc_cell_pct(x):
    """Shaded accuracy cell in percent format, e.g. \cellcolor{blue!24}60\%."""
    return rf"\cellcolor{{blue!{_acc_shade(x)}}}{x * 100:.0f}\%"


def fmt_gap_cell_pct(gap):
    """Shaded gap cell in percent format, e.g. \cellcolor{red!10}+5\%."""
    sign = "+" if gap >= 0 else "$-$"
    return rf"\cellcolor{{red!{_gap_shade(gap)}}}{sign}{abs(gap) * 100:.0f}\%"

LORA_ARB_RESULTS_GLOB = str(_ROOT / "lora_intervention" / "results" / "main_eval_*.json")
LORA_SEM_VAL = _ROOT / "lora_sem_validation_results.json"
LORA_SEM_FINISH = _ROOT / "lora_sem_finish_results.json"


def fmt_pct(x):
    """Format a [0, 1] float as a percentage string with no decimal places."""
    return f"{x * 100:.0f}\\%"


def fmt_gap(g):
    sign = "+" if g >= 0 else "$-$"
    return f"{sign}{abs(g) * 100:.0f}\\%"


def load_lora_arb_baseline():
    """Pull baseline ARB numbers from the comparison file authored by the
    LoRA run.  Format: rows of `Cell  BSE RI  BSE PI  BSE gap  FT RI  FT PI  FT gap  verdict`.
    """
    comp_path = _ROOT / "lora_intervention" / "results" / "main_comparison.txt"
    if not comp_path.exists():
        return {}
    out = {}
    for line in comp_path.read_text().splitlines():
        s = line.strip()
        if not s or s.startswith("=") or s.startswith("-") or s.startswith("Fixed:"):
            continue
        if s.startswith("Cell") or "COMPARISON" in s:
            continue
        # Tokenize: e.g. "7k_ 30u  50%  38%  +12%   100%   100%  +0%   ✓ FIXED"
        parts = s.split()
        if len(parts) < 7:
            continue
        # parts[0] like "7k_", parts[1] like "30u"
        try:
            k_token = parts[0].rstrip("k_").rstrip("k")
            n_token = parts[1].rstrip("u")
            K = int(k_token); N = int(n_token)
        except (ValueError, IndexError):
            continue
        # base RI/PI/gap, then FT RI/PI/gap
        def _pct(t): return float(t.strip("+%-")) / 100.0 * (-1 if t.startswith("-") else 1)
        try:
            b_ri = float(parts[2].rstrip("%")) / 100.0
            b_pi = float(parts[3].rstrip("%")) / 100.0
            b_gap = float(parts[4].rstrip("%").replace("+", "")) / 100.0
            f_ri = float(parts[5].rstrip("%")) / 100.0
            f_pi = float(parts[6].rstrip("%")) / 100.0
            f_gap = float(parts[7].rstrip("%").replace("+", "")) / 100.0
        except (ValueError, IndexError):
            continue
        out[(K, N)] = {
            "base_ri": b_ri, "base_pi": b_pi, "base_gap": b_gap,
            "lora_ri": f_ri, "lora_pi": f_pi, "lora_gap": f_gap,
        }
    return out


DISPLAY_CELLS = [
    (7, 30), (7, 50), (10, 30), (10, 50),
    (15, 20), (15, 30), (15, 50),
    (20, 30), (20, 50), (20, 75),
    (25, 30), (25, 50), (25, 75),
    (30, 30), (30, 50), (30, 75),
]


def make_lora_arb_table_compact(out_path):
    """Compact 3-column table for the main body: $(K, N)$, base gap, +LoRA gap.
    Strips FVQ/CVQ breakdown to fit a single column.
    Full breakdown lives in `tab_lora_arb_full.tex`.
    """
    rows = load_lora_arb_baseline()
    if not rows:
        print("  WARNING: no LoRA ARB baseline rows found")
        return
    lines = [
        "% Auto-generated by paper/scripts/generate_lora_tables.py",
        "% LoRA on Qwen2.5-3B-Instruct, held-out ARB cells (compact body version)",
        r"\begin{tabular}[t]{lcc}",
        r"\toprule",
        r"$(K, N)$ & \textbf{Base gap} & \textbf{+ LoRA gap} \\",
        r"\midrule",
    ]
    for K, N in DISPLAY_CELLS:
        r = rows.get((K, N))
        if r is None:
            lines.append(f"  $({K}, {N})$ & --- & --- \\\\")
            continue
        lines.append(
            f"  $({K}, {N})$ & {fmt_gap_cell_pct(r['base_gap'])} & {fmt_gap_cell_pct(r['lora_gap'])} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"  saved {out_path}")


def make_lora_arb_table_full(out_path):
    """Full table (FVQ, CVQ, gap before and after) for the appendix."""
    rows = load_lora_arb_baseline()
    if not rows:
        print("  WARNING: no LoRA ARB baseline rows found")
        return
    lines = [
        "% Auto-generated by paper/scripts/generate_lora_tables.py",
        "% LoRA on Qwen2.5-3B-Instruct, full breakdown for appendix",
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r" & \multicolumn{3}{c}{\textbf{Base}} & \multicolumn{3}{c}{\textbf{+ LoRA}} \\",
        r"\cmidrule(lr){2-4} \cmidrule(lr){5-7}",
        r"$(K, N)$ & FVQ & CVQ & gap & FVQ & CVQ & gap \\",
        r"\midrule",
    ]
    for K, N in DISPLAY_CELLS:
        r = rows.get((K, N))
        if r is None:
            lines.append(f"  $({K}, {N})$ & --- & --- & --- & --- & --- & --- \\\\")
            continue
        lines.append(
            f"  $({K}, {N})$ & "
            f"{fmt_acc_cell_pct(r['base_ri'])} & {fmt_acc_cell_pct(r['base_pi'])} & {fmt_gap_cell_pct(r['base_gap'])} & "
            f"{fmt_acc_cell_pct(r['lora_ri'])} & {fmt_acc_cell_pct(r['lora_pi'])} & {fmt_gap_cell_pct(r['lora_gap'])} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"  saved {out_path}")


def make_lora_arb_table(out_path):
    """Back-compat wrapper: builds both versions."""
    make_lora_arb_table_compact(out_path)
    full_path = Path(str(out_path).replace(".tex", "_full.tex"))
    make_lora_arb_table_full(full_path)


def make_lora_sem_table(out_path):
    """SEM OOD: 4 held-out cells, base vs LoRA."""
    if not LORA_SEM_VAL.exists() or not LORA_SEM_FINISH.exists():
        print("  WARNING: SEM OOD JSONs not found")
        return
    val = json.loads(LORA_SEM_VAL.read_text())
    finish = json.loads(LORA_SEM_FINISH.read_text())

    base = val["baseline"]
    lora_first_two = val["lora"]
    lora_last_two = finish["lora"]

    lines = [
        "% Auto-generated by paper/scripts/generate_lora_tables.py",
        "% LoRA trained on ARB; evaluated on SEM (cross-distribution transfer)",
        r"\begin{tabular}[t]{lcccccc}",
        r"\toprule",
        r" & \multicolumn{3}{c}{\textbf{Base}} & \multicolumn{3}{c}{\textbf{+ LoRA (ARB-trained)}} \\",
        r"\cmidrule(lr){2-4} \cmidrule(lr){5-7}",
        r"$(K, N)$ & FVQ & CVQ & gap & FVQ & CVQ & gap \\",
        r"\midrule",
    ]
    cell_keys = [(7, 20), (15, 20), (15, 30), (20, 30)]
    for K, N in cell_keys:
        key = f"{K}_{N}"
        b = base.get(key)
        # Cells (7,20) and (15,20) are in lora_first_two; (15,30) and (20,30) in lora_last_two
        ln = lora_first_two.get(key) or lora_last_two.get(key)
        if b is None or ln is None:
            lines.append(f"  $({K}, {N})$ & --- & --- & --- & --- & --- & --- \\\\")
            continue
        lines.append(
            f"  $({K}, {N})$ & "
            f"{fmt_acc_cell_pct(b['fvq_acc'])} & {fmt_acc_cell_pct(b['cvq_acc'])} & {fmt_gap_cell_pct(b['gap'])} & "
            f"{fmt_acc_cell_pct(ln['fvq_acc'])} & {fmt_acc_cell_pct(ln['cvq_acc'])} & {fmt_gap_cell_pct(ln['gap'])} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    Path(out_path).write_text("\n".join(lines) + "\n")
    print(f"  saved {out_path}")


def main():
    print(f"Generating LoRA tables to {OUT_DIR} …")
    make_lora_arb_table(OUT_DIR / "tab_lora_arb.tex")
    make_lora_sem_table(OUT_DIR / "tab_lora_sem.tex")
    print("Done.")


if __name__ == "__main__":
    main()
